module.exports = {
  Pakenham: [
    'Flinders Street',
    'Southern Cross',
    'Flagstaff',
    'Melbourne Central',
    'Parliament',
    'Richmond',
    'South Yarra',
    'Hawksburn',
    'Toorak',
    'Armadale',
    'Malvern',
    'Caulfield',
    'Carnegie',
    'Murrumbeena',
    'Hughesdale',
    'Oakleigh',
    'Huntingdale',
    'Clayton',
    'Westall',
    'Springvale',
    'Sandown Park',
    'Noble Park',
    'Yarraman',
    'Dandenong',
    'Hallam',
    'Narre Warren',
    'Berwick',
    'Beaconsfield',
    'Officer',
    'Cardinia Road',
    'Pakenham'
  ],
  Upfield: [
    'Flinders Street',
    'Parliament',
    'Melbourne Central',
    'Flagstaff',
    'North Melbourne',
    'Macaulay',
    'Flemington Bridge',
    'Royal Park',
    'Jewell',
    'Brunswick',
    'Anstey',
    'Moreland',
    'Coburg',
    'Batman',
    'Merlynston',
    'Fawkner',
    'Gowrie',
    'Upfield'
  ],
  Cranbourne: [
    'Flinders Street',
    'Southern Cross',
    'Flagstaff',
    'Melbourne Central',
    'Parliament',
    'Richmond',
    'South Yarra',
    'Hawksburn',
    'Toorak',
    'Armadale',
    'Malvern',
    'Caulfield',
    'Carnegie',
    'Murrumbeena',
    'Hughesdale',
    'Oakleigh',
    'Huntingdale',
    'Clayton',
    'Westall',
    'Springvale',
    'Sandown Park',
    'Noble Park',
    'Yarraman',
    'Dandenong',
    'Lynbrook',
    'Merinda Park',
    'Cranbourne'
  ],
  'Stony Point': [
    'Flinders Street',
    'Southern Cross',
    'Flagstaff',
    'Melbourne Central',
    'Parliament',
    'Richmond',
    'South Yarra',
    'Hawksburn',
    'Toorak',
    'Armadale',
    'Malvern',
    'Caulfield',
    'Glenhuntly',
    'Ormond',
    'McKinnon',
    'Bentleigh',
    'Patterson',
    'Moorabbin',
    'Highett',
    'Southland',
    'Cheltenham',
    'Mentone',
    'Parkdale',
    'Mordialloc',
    'Aspendale',
    'Edithvale',
    'Chelsea',
    'Bonbeach',
    'Carrum',
    'Seaford',
    'Kananook',
    'Frankston',
    'Leawarra',
    'Baxter',
    'Somerville',
    'Tyabb',
    'Hastings',
    'Bittern',
    'Morradoo',
    'Crib Point',
    'Stony Point'
  ],
  Sandringham: [
    'Flinders Street',
    'Southern Cross',
    'Flagstaff',
    'Melbourne Central',
    'Parliament',
    'Richmond',
    'South Yarra',
    'Prahran',
    'Windsor',
    'Balaclava',
    'Ripponlea',
    'Elsternwick',
    'Gardenvale',
    'North Brighton',
    'Middle Brighton',
    'Brighton Beach',
    'Hampton',
    'Sandringham'
  ],
  Williamstown: [
    'Flinders Street',
    'Parliament',
    'Melbourne Central',
    'Flagstaff',
    'North Melbourne',
    'South Kensington',
    'Footscray',
    'Seddon',
    'Yarraville',
    'Spotswood',
    'Newport',
    'North Williamstown',
    'Williamstown Beach',
    'Williamstown'
  ],
  Werribee: [
    'Flinders Street',
    'Parliament',
    'Melbourne Central',
    'Flagstaff',
    'North Melbourne',
    'South Kensington',
    'Footscray',
    'Seddon',
    'Yarraville',
    'Spotswood',
    'Newport',
    'Seaholme',
    'Altona',
    'Westona',
    'Paisley',
    'Galvin',
    'Laverton',
    'Aircraft',
    'Williams Landing',
    'Hoppers Crossing',
    'Werribee'
  ],
  Craigieburn: [
    'Flinders Street',
    'Parliament',
    'Melbourne Central',
    'Flagstaff',
    'North Melbourne',
    'Kensington',
    'Newmarket',
    'Ascot Vale',
    'Moonee Ponds',
    'Essendon',
    'Glenbervie',
    'Strathmore',
    'Pascoe Vale',
    'Oak Park',
    'Glenroy',
    'Jacana',
    'Broadmeadows',
    'Coolaroo',
    'Roxburgh Park',
    'Craigieburn'
  ],
  Belgrave: [
    'Flinders Street',
    'Southern Cross',
    'Flagstaff',
    'Melbourne Central',
    'Parliament',
    'Richmond',
    'East Richmond',
    'Burnley',
    'Hawthorn',
    'Glenferrie',
    'Auburn',
    'Camberwell',
    'East Camberwell',
    'Canterbury',
    'Chatham',
    'Surrey Hills',
    'Mont Albert',
    'Box Hill',
    'Laburnum',
    'Blackburn',
    'Nunawading',
    'Mitcham',
    'Heatherdale',
    'Ringwood',
    'Heathmont',
    'Bayswater',
    'Boronia',
    'Ferntree Gully',
    'Upper Ferntree Gully',
    'Upwey',
    'Tecoma',
    'Belgrave'
  ],
  Lilydale: [
    'Flinders Street',
    'Southern Cross',
    'Flagstaff',
    'Melbourne Central',
    'Parliament',
    'Richmond',
    'East Richmond',
    'Burnley',
    'Hawthorn',
    'Glenferrie',
    'Auburn',
    'Camberwell',
    'East Camberwell',
    'Canterbury',
    'Chatham',
    'Surrey Hills',
    'Mont Albert',
    'Box Hill',
    'Laburnum',
    'Blackburn',
    'Nunawading',
    'Mitcham',
    'Heatherdale',
    'Ringwood',
    'Ringwood East',
    'Croydon',
    'Mooroolbark',
    'Lilydale'
  ],
  Sunbury: [
    'Flinders Street',
    'Parliament',
    'Melbourne Central',
    'Flagstaff',
    'North Melbourne',
    'South Kensington',
    'Footscray',
    'Middle Footscray',
    'West Footscray',
    'Tottenham',
    'Sunshine',
    'Albion',
    'Ginifer',
    'St. Albans',
    'Keilor Plains',
    'Watergardens',
    'Diggers Rest',
    'Sunbury',
  ],
  Alamein: [
    'Flinders Street',
    'Flagstaff',
    'Melbourne Central',
    'Parliament',
    'Richmond',
    'East Richmond',
    'Burnley',
    'Hawthorn',
    'Glenferrie',
    'Auburn',
    'Camberwell',
    'Riversdale',
    'Willison',
    'Hartwell',
    'Burwood',
    'Ashburton',
    'Alamein'
  ],
  Mernda: [
    'Flinders Street',
    'Flagstaff',
    'Melbourne Central',
    'Parliament',
    'Jolimont',
    'West Richmond',
    'North Richmond',
    'Collingwood',
    'Victoria Park',
    'Clifton Hill',
    'Rushall',
    'Merri',
    'Northcote',
    'Croxton',
    'Thornbury',
    'Bell',
    'Preston',
    'Regent',
    'Reservoir',
    'Ruthven',
    'Keon Park',
    'Thomastown',
    'Lalor',
    'Epping',
    'South Morang',
    'Middle Gorge',
    'Hawkstowe',
    'Mernda'
  ],
  Hurstbridge: [
    'Flinders Street',
    'Flagstaff',
    'Melbourne Central',
    'Parliament',
    'Jolimont',
    'West Richmond',
    'North Richmond',
    'Collingwood',
    'Victoria Park',
    'Clifton Hill',
    'Westgarth',
    'Dennis',
    'Fairfield',
    'Alphington',
    'Darebin',
    'Ivanhoe',
    'Eaglemont',
    'Heidelberg',
    'Rosanna',
    'Macleod',
    'Watsonia',
    'Greensborough',
    'Montmorency',
    'Eltham',
    'Diamond Creek',
    'Wattle Glen',
    'Hurstbridge'
  ],
  'Glen Waverley': [
    'Flinders Street',
    'Flagstaff',
    'Melbourne Central',
    'Parliament',
    'Richmond',
    'East Richmond',
    'Burnley',
    'Heyington',
    'Kooyong',
    'Tooronga',
    'Gardiner',
    'Glen Iris',
    'Darling',
    'East Malvern',
    'Holmesglen',
    'Jordanville',
    'Mount Waverley',
    'Syndal',
    'Glen Waverley'
  ],
  'Flemington Racecourse': [
    'Flinders Street',
    'Parliament',
    'Melbourne Central',
    'Flagstaff',
    'North Melbourne',
    'Kensington',
    'Newmarket',
    'Showgrounds',
    'Flemington Racecourse'
  ],
  Newport: [
    'Flinders Street',
    'Southern Cross',
    'North Melbourne',
    'South Kensington',
    'Footscray',
    'Seddon',
    'Yarraville',
    'Spotswood',
    'Newport'
  ],
  'Melbourne Yard': [
    'Flinders Street',
    'Southern Cross',
    'Melbourne Yard Stabling Sidings'
  ],
  'South Dynon Loco': [
    'South Dynon',
    'West Tower',
    'Southern Cross',
    'Flinders Street'
  ]
}
